name: Deploy to EC2

on:
  push:
    branches:
      - develop  # solo pull a develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_DEPLOY_KEY }}
          port: 22
          script: |
            cd ~/webServer/Web
            git fetch origin develop
            git reset --hard origin/develop
            pip3 install -r requirements.txt
            sudo systemctl restart fastapi.service

